version: "3.4"

networks:
  geogoremad:
    driver: bridge

services:
  geogoremad.postgis.dev:
    image: kartoza/postgis:11.5-2.8
    container_name: geogoremad_postgis_dev
    restart: unless-stopped
    volumes:
      - ./data/geogoremad_postgis:/var/lib/postgresql
    env_file:
      - .env.postgis
    environment:
      - DEFAULT_ENCODING=LATIN1
      - DEFAULT_COLLATION=es_ES.iso88591
      - DEFAULT_CTYPE=es_ES.iso88591
    ports:
      - 9100:5432
    networks:
      - geogoremad

  geogoremad.pgadmin.dev:
    image: dpage/pgadmin4:6
    container_name: geogoremad_pgadmin_dev
    restart: unless-stopped
    volumes:
      - ./data/geogoremad_pgadmin:/var/lib/pgadmin
    env_file:
      - .env.pgadmin
    depends_on:
      - geogoremad.postgis
    ports:
      - 9102:80
    networks:
      - geogoremad
