version: "3.4"

networks:
  geogoremad:
    driver: bridge

services:
  geogoremad.postgis:
    image: kartoza/postgis:11.5-2.8
    container_name: geogoremad-postgis
    restart: unless-stopped
    volumes:
      - ./data/postgis:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=ficticio
      - POSTGRES_DBNAME=geogoremad-desarrollo
      - DEFAULT_ENCODING=LATIN1
      - DEFAULT_COLLATION=es_ES.iso88591
      - DEFAULT_CTYPE=es_ES.iso88591
    ports:
      - 5432:5432
    networks:
      - geogoremad

  geogoremad.pgadmin:
    image: dpage/pgadmin4:6
    container_name: geogoremad-pgadmin
    restart: unless-stopped
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@ficticio.com
      - PGADMIN_DEFAULT_PASSWORD=ficticio
    depends_on:
      - geogoremad.postgis
    ports:
      - 9001:80
    networks:
      - geogoremad
